import { contextBridge, ipcRenderer } from 'electron'

contextBridge.exposeInMainWorld('electronAPI', {
  invoke: (channel: string, ...args: unknown[]) => {
    const allowedChannels = [
      'auth:login',
      'auth:getCurrentUser',
      'auth:logout',
      'auth:changePassword',
      'users:list',
      'users:get',
      'users:create',
      'users:update',
      'users:deactivate',
      'users:resetPassword',
      'activityLog:list',
      'vendors:list',
      'vendors:get',
      'vendors:create',
      'vendors:update',
      'vendors:toggleActive',
      'vendors:ledger',
      'vendors:balance',
      'vendors:summary',
      'customers:list',
      'customers:get',
      'customers:create',
      'customers:update',
      'customers:toggleActive',
      'customers:ledger',
      'customers:balance',
      'customers:summary',
      'customers:projects',
      'settings:get',
      'settings:save',
      'settings:logo:upload',
      'inventory:listUnits',
      'inventory:createUnit',
      'inventory:updateUnit',
      'inventory:deleteUnit',
      'inventory:listCategories',
      'inventory:createCategory',
      'inventory:updateCategory',
      'inventory:deleteCategory',
      'inventory:listWarehouses',
      'inventory:createWarehouse',
      'inventory:updateWarehouse',
      'inventory:toggleWarehouse',
      'inventory:listItems',
      'inventory:getItem',
      'inventory:createItem',
      'inventory:updateItem',
      'inventory:toggleItem',
      'inventory:getItemStock',
      'inventory:getAllStockLevels',
      'inventory:getItemStockHistory',
      'inventory:adjustStock',
      'inventory:getLowStockItems',
      'inventory:listAllStockMovements',
      'po:create',
      'po:list',
      'po:getById',
      'po:update',
      'po:updateStatus',
      'po:delete',
      'pi:create',
      'pi:list',
      'pi:getById',
      'pi:void',
      'pi:getOutstanding',
      'payment:record',
      'payment:list',
      'payment:getById',
      'projects:list',
      'projects:get',
      'projects:create',
      'projects:update',
      'projects:updateStatus',
      'projects:issueMaterial',
      'projects:returnMaterial',
      'projects:getMaterials',
      'projects:addLaborCost',
      'projects:getLaborCosts',
      'projects:addExpense',
      'projects:getExpenses',
      'projects:profitability',
      'projects:summary',
      'invoices:list',
      'invoices:get',
      'invoices:create',
      'invoices:update',
      'invoices:delete',
      'accounting:list',
      'accounting:get',
      'accounting:create',
      'accounting:update',
      'accounting:delete',
      'hr:list',
      'hr:get',
      'hr:create',
      'hr:update',
      'hr:delete',
      'reports:run',
      'bom:create',
      'bom:list',
      'bom:getById',
      'bom:update',
      'bom:deactivate',
      'bom:costEstimate',
      'fab:create',
      'fab:list',
      'fab:getById',
      'fab:start',
      'fab:complete',
      'fab:cancel',
    ]
    if (allowedChannels.includes(channel)) {
      return ipcRenderer.invoke(channel, ...args)
    }
    throw new Error(`Unauthorized IPC channel: ${channel}`)
  },
})

declare global {
  interface Window {
    electronAPI: {
      invoke: (channel: string, ...args: unknown[]) => Promise<unknown>
    }
  }
}
